"""auto update

Revision ID: 65283b70e82d
Revises: 
Create Date: 2026-09-22 02:10:54.383383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65283b70e82d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forge_session_locks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('device_label', sa.String(), nullable=True),
    sa.Column('heartbeat_at', sa.String(), nullable=True),
    sa.Column('released', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forge_session_locks_id'), 'forge_session_locks', ['id'], unique=False)
    op.create_index(op.f('ix_forge_session_locks_user_id'), 'forge_session_locks', ['user_id'], unique=False)
    op.create_table('forge_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('version_index', sa.Integer(), nullable=False),
    sa.Column('html', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('revision_prompt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forge_versions_id'), 'forge_versions', ['id'], unique=False)
    op.create_index(op.f('ix_forge_versions_user_id'), 'forge_versions', ['user_id'], unique=False)
    op.create_index(op.f('ix_forge_versions_workspace_id'), 'forge_versions', ['workspace_id'], unique=False)
    op.create_table('forge_workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('plan_json', sa.String(), nullable=True),
    sa.Column('pending_revision', sa.String(), nullable=True),
    sa.Column('active_version_id', sa.Integer(), nullable=True),
    sa.Column('version_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forge_workspaces_active_version_id'), 'forge_workspaces', ['active_version_id'], unique=False)
    op.create_index(op.f('ix_forge_workspaces_id'), 'forge_workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_forge_workspaces_user_id'), 'forge_workspaces', ['user_id'], unique=False)
    op.create_table('oidc_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('nonce', sa.String(length=255), nullable=False),
    sa.Column('code_verifier', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oidc_states_id'), 'oidc_states', ['id'], unique=False)
    op.create_index(op.f('ix_oidc_states_state'), 'oidc_states', ['state'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_oidc_states_state'), table_name='oidc_states')
    op.drop_index(op.f('ix_oidc_states_id'), table_name='oidc_states')
    op.drop_table('oidc_states')
    op.drop_index(op.f('ix_forge_workspaces_user_id'), table_name='forge_workspaces')
    op.drop_index(op.f('ix_forge_workspaces_id'), table_name='forge_workspaces')
    op.drop_index(op.f('ix_forge_workspaces_active_version_id'), table_name='forge_workspaces')
    op.drop_table('forge_workspaces')
    op.drop_index(op.f('ix_forge_versions_workspace_id'), table_name='forge_versions')
    op.drop_index(op.f('ix_forge_versions_user_id'), table_name='forge_versions')
    op.drop_index(op.f('ix_forge_versions_id'), table_name='forge_versions')
    op.drop_table('forge_versions')
    op.drop_index(op.f('ix_forge_session_locks_user_id'), table_name='forge_session_locks')
    op.drop_index(op.f('ix_forge_session_locks_id'), table_name='forge_session_locks')
    op.drop_table('forge_session_locks')
    # ### end Alembic commands ###